### ISSUE TITLE
more locales?

### ISSUE THREAD

**Issue by denniskim** [milesj/emojibase#10]
Hey, Miles. I'd like to use your emoji datasets in a project, but I need support for locales you haven't converted CLDR data for. I've examined your conversion scripts, and they seem to reference some libraries not included in the repo, so I haven't attempted to run them myself. Could I make a request for some locales?

**Comment by milesj** [comment]
Sup Dennis!

What locales do you require? Supported list is here: http://www.unicode.org/repos/cldr/tags/release-32/common/annotations/

**Comment by denniskim** [comment]
(Long time, Miles!)
I would need:

en_GB
es_MX
pl
pt
th
zh_Hant

**Comment by milesj** [comment]
Can do! I'll tackle this tonight.

**Comment by denniskim** [comment]
Awesome. Thanks!

**Comment by milesj** [comment]
I've got the locale data built but the region based locales have a bit of undefined data, so digging into it a bit more.

**Comment by denniskim** [comment]
Ok. Let me know if there's anything I can do to help.

**Comment by milesj** [comment]
Got it working. Looks like keycap 10 was the only one missing data.

```
diff --git a/packages/emojibase-data/da/compact.json b/packages/emojibase-data/da/compact.json
index 3463cac..1e07565 100644
--- a/packages/emojibase-data/da/compact.json
+++ b/packages/emojibase-data/da/compact.json
@@ -29108,12 +29108,16 @@
     "unicode": "9️⃣"
   },
   {
+    "annotation": "keycap: 10",
     "group": 6,
     "hexcode": "1F51F",
     "order": 3032,
     "shortcodes": [
       "ten"
     ],
+    "tags": [
+      "keycap"
+    ],
     "unicode": "🔟"
   },
   {
```

**Comment by milesj** [comment]
New locales added! Enjoy.

**Comment by denniskim** [comment]
sweet.
