### ISSUE TITLE
Supporting Unicode Emoji 14?

### ISSUE THREAD

**Issue by b-g** [milesj/emojibase#102]
Hi @milesj, as usual we are wondering whether and when emojibase will be supporting Unicode Emoji 14? :) Any timeline? Sorry to bother and many thanks for all the good work! 🙏

**Comment by b-g** [comment]
Many thanks! I see ... will keep an eye on it too.

**Comment by milesj** [comment]
Landing soon https://github.com/milesj/emojibase/pull/129

**Comment by b-g** [comment]
Hi @milesj! Is emojibase-data 7.0.0 published? The [Changelog](https://github.com/milesj/emojibase/blob/master/packages/data/CHANGELOG.md#700) seems to be saying so, but `npm install emojibase-data@7.0.0` fails. What did I miss? Cheers!

**Comment by milesj** [comment]
@b-g It hasn't released yet (no date in the changelog). I'm waiting for the final CLDR 40 to release, which is the end of October.

**Comment by b-g** [comment]
I see! Sorry for my confusion! Much looking forward to!
