### ISSUE TITLE
emoji meta for zh-Hant is showing zh

### ISSUE THREAD

**Issue by roderickhsiao** [milesj/emojibase#107]
https://github.com/milesj/emojibase/blob/master/packages/data/zh-hant/meta.raw.json

The content is showing simplified Chinese (zh) instead of Traditional (zh-hant)

probably https://github.com/milesj/emojibase/pull/87/files#diff-d97ea88b1ef5b93bd52dff5ebd3cf282c6d2ab509147fd0358e52df8de0753e7L11 ?

Or is the unicode doesn't have the data?

**Comment by milesj** [comment]
Yeah I may have overridden it on accident 😅 

Open to contributions on this one.

**Comment by roderickhsiao** [comment]
Ha, no big deal :), I'll check if I can run the repo locally and help fixing it 💪

**Comment by roderickhsiao** [comment]
https://github.com/milesj/emojibase/blob/master/packages/data/zh-hant/data.raw.json thanks!
