### ISSUE TITLE
irregular/incorrect data?

### ISSUE THREAD

**Issue by denniskim** [milesj/emojibase#11]
I noticed that there are no tags for the "keycap ten" emoji in both data.json and compact.json (hex: 1F51F; shortcode: ten). The other keycaps have at least the tag "keycap".

It also seems to be the only character that has no "tags" property at all.

**Comment by milesj** [comment]
Might be related to the annotation inconsistencies I found yesterday. Will look into.

**Comment by denniskim** [comment]
I just noticed it's missing the "annotation" property, as well in both JSON files.

**Comment by milesj** [comment]
Looks like the annotation and tags exist here: http://unicode.org/repos/cldr/tags/release-32/common/annotationsDerived/en.xml

**Comment by milesj** [comment]
This is fixed! Thanks for finding.
