### ISSUE TITLE
A bad case

### ISSUE THREAD

**Issue by zhangzhiqiang37** [milesj/emojibase#114]
👁‍🗨  this emoji character code in iOS is "\uD83D\uDC41\u200D\uD83D\uDDE8"
emojibase-regex can not match it

the code is different between 👁️‍🗨️  and 👁‍🗨  though they look the same

**Comment by zhangzhiqiang37** [comment]
Yeah, it works.
Thanks~

**Comment by milesj** [comment]
Awesome
