### ISSUE TITLE
More emoji list data in test utils?

### ISSUE THREAD

**Issue by zhangzhiqiang37** [milesj/emojibase#115]
There can input "minimally-qualified" or "unqualified" emoji in Some devices
so, I suggest that you can provide a function to get full emoji data include "unqualified" and "minimally-qualified" emoji

e.g. #114

**Comment by milesj** [comment]
@zhangzhiqiang37 This library is based on the official Unicode data (https://unicode.org/Public/emoji/13.1/), so anything that is not found in these data files will unfortunately not be supported.

**Comment by zhangzhiqiang37** [comment]
@milesj You can read `emoji-test.txt` in the list（https://unicode.org/Public/emoji/13.1/）, they list all emoji case include "unqualified" and "minimally-qualified"
In order to cover "all emoji case", or cover "more emoji case", I think it is necessary to provice a way to get all emoji

**Comment by milesj** [comment]
@zhangzhiqiang37 Sorry misunderstood your question. Are you looking for the hexcodes specifically? Or the emoji characters?

**Comment by zhangzhiqiang37** [comment]
I suggest that you can provide a function(like getAllEmojiList) to get all emoji data include "unqualified" and "minimally-qualified" emoji.
So others can test their program to ensure match all cases

**Comment by milesj** [comment]
@zhangzhiqiang37 So the `emoji` field in each object is the fully-qualified unicode character, while the `text` is the unqualified one. 

However, I don't think this is applied everywhere, so I can definitely update it.

**Comment by milesj** [comment]
This has landed.
