### ISSUE TITLE
`:P` should also be an emoticon for `😛`

### ISSUE THREAD

**Issue by SimonBrandner** [milesj/emojibase#122]
Discord and others do this, so it seems to make sense for consistency

**Comment by SimonBrandner** [comment]
This seems to be a more general issue - a bunch of lower-case emoticons are often also used upper-case, so I am not sure what would be the correct way to handle this from the dataset perspective.

**Comment by milesj** [comment]
@SimonBrandner Since I'm working on the next major version, I can update this to differentiate. Open to any suggestions for pairing emoticons and emojis.

**Comment by SimonBrandner** [comment]
I generally think that _some_ emoticons should match no matter the casing (`:p`, `:o`). In [Element Web](https://github.com/vector-im/element-web) and specifically in the [matrix-react-sdk](https://github.com/matrix-org/matrix-react-sdk), we also match emoticons converted to upper-case to solve this.

That being said, I don't know much about how `emojibase` works and I don't know, if this could be fixed in it

**Comment by milesj** [comment]
Added

**Comment by SimonBrandner** [comment]
> Added

Thank you!
