### ISSUE TITLE
Feature request: make the CDN url configurable

### ISSUE THREAD

**Issue by npeterkamps** [milesj/emojibase#139]
Would you be open to (a PR) adding the CDN url to the `FetchFromCDNOptions`?

Because of security policies, we want to host the emoji data on our own CDN. It would be great if I can keep using this package with its caching capabilities and simply give it a different URL to load the data from.

Something along the lines of:
```ts
// types.ts
export interface FetchFromCDNOptions extends RequestInit {
	/** Cache the response in local storage instead of session storage. Defaults to `false`. */
	local?: boolean;
	/** The url from which to load the JSON files */
	cdnUrl?: string;
	/** The release version to fetch. Defaults to `latest`. */
	version?: string;
}

// fetchFromCDN.ts
export async function fetchFromCDN<T>(path: string, options: FetchFromCDNOptions = {}): Promise<T> {
	const {
		local = false,
		cdnUrl = 'https://cdn.jsdelivr.net/npm/emojibase-data@',
		version = 'latest',
		...opts,
	} = options;

	...

	// eslint-disable-next-line compat/compat
	const response = await fetch(`${cdnUrl}${version}/${path}`, {
		credentials: 'omit',
		mode: 'cors',
		redirect: 'error',
		...opts,
	});
```

It could also be worth considering making it a function that receives `version` and `path`, so developers get more flexibility of how to organize their own CDN.

**Comment by milesj** [comment]
@npeterkamps Sounds good to me 👍 

Supporting a string or function sounds best.
