### ISSUE TITLE
[iamcal] :rofl: `:rofl:` alias

### ISSUE THREAD

**Issue by 42Willow** [milesj/emojibase#156]
Currently `:rolling_on_the_floor_laughing:` is used instead of `:rofl:` for the :rofl: emoji.

**Comment by milesj** [comment]
@42Willow What shortcode preset and language you are using?

**Comment by 42Willow** [comment]
I'm not sure what short code preset I'm using, but my Windows display language is set to `English (Australia)`. How do I find that out?

**Comment by milesj** [comment]
@42Willow Yeah unfortunately, I don't control iamcal's shortcodes. Those are a 3rd-party from here: https://github.com/iamcal/emoji-data

I just include them as an option in emojibase. You may want to report an issue on that repo.
