### ISSUE TITLE
Emoji regex don't work for not colored 👍

### ISSUE THREAD

**Issue by misha-erm** [milesj/emojibase#159]
Hello, 

I was testing the emoji regex and noticed that it doesn't match thumbs up emoji if it doesn't have skin color

```
const EMOJI_REGEX = require('emojibase-regex/emoji');

console.log('Match for 👍🏻 :', '👍🏻'.match(EMOJI_REGEX)) //  ->  Match for 👍🏻 : [ '👍🏻', index: 0, input: '👍🏻', groups: undefined ]
console.log('Match for 👍 :','👍'.match(EMOJI_REGEX)) //  -> Match for 👍 : null
```

Here is a link to REPL https://replit.com/@MikeYermolayev/emojibase-regex-repro 

Thank you

**Comment by robintown** [comment]
The issue in other words: https://github.com/milesj/emojibase/issues/174

**Comment by milesj** [comment]
This is a bit weird since we have tests that check _all_ emojis: https://github.com/milesj/emojibase/blob/master/packages/regex/tests/regex.test.ts#L67

**Comment by milesj** [comment]
Ok yeah, I misread the post. Yeah `emoji` regex requires a variant modifier, which 👍 does not have. So you want `emoji-loose`.

This is "working as intended" right now, but I think in the next version I'm going to remove the loose regex as it causes confusion.
