### ISSUE TITLE
Categories all over the place?

### ISSUE THREAD

**Issue by raulriera** [milesj/emojibase#16]
It seems that the categories are all mixed up, the first category (smiley and faces) goes all the way across several other ones, including animals and objects like a diamond jewel.

Actually every single category in this file is different from what you will find in the emoji keyboards, websites, etc. its here a reason for this?

**Comment by milesj** [comment]
@raulriera I'm almost positive all those other sites are wrong. The official specification can be found here: http://unicode.org/emoji/charts/emoji-list.html Diamond is under the sub-group "Clothing", which is under the group "Person", which is the "Smileys & People" you are seeing.

If this is not what you're seeing, can you send me a screenshot?

**Comment by milesj** [comment]
@raulriera Yeah, most likely, it's the Apple way... That being said, this repo follows the spec, so if you'd like to re-order it, you'll have to do it yourself.
