### ISSUE TITLE
order

### ISSUE THREAD

**Issue by stet** [milesj/emojibase#160]
Curious to understand the order property. Is this opinionated or based on Unicode Standard suggestion? 

https://emojibase.dev/api/emojibase/interface/Emoji/#order

Is there a resource on unicode website that you can provide?

Thanks!

**Comment by milesj** [comment]
@stet This is provided by Unicode. http://unicode.org/Public/emoji/15.0/emoji-test.txt

**Comment by stet** [comment]
Thanks @milesj I understand now. I assume the "display" order never changes and no shifting? 

Is there any condensed data available on each emoji release date and an order/ID based on this? I don't believe so. 

Appreciate emojibase, thank you for this 🫡👊

**Comment by milesj** [comment]
@stet It does change/shift between releases. Not always, but has happened a few times.

But yes, I don't keep track of this. You would need to compare each version manually.
