### ISSUE TITLE
Error fetching emojis: Error: Failed to load Emojibase dataset.

### ISSUE THREAD

**Issue by shinokada** [milesj/emojibase#168]
I'm just trying out emojibase. 
According to the doc, 

> Fetches and returns a localized list of emojis (and optional shortcodes) from our CDN. Uses fetchFromCDN and fetchShortcodes under the hood.

I have the following but I get Error fetching emojis error. Can you point out what I am doing wrong?

```
import { fetchEmojis } from 'emojibase';

async function getEmojis() {
  try {
    const emojis = await fetchEmojis('ja', {
      compact: true,
      shortcodes: ['cldr'],
      version: '2.1.3',
    });

    // Do something with the emojis
    console.log(emojis);
  } catch (error) {
    // Handle errors
    console.error('Error fetching emojis:', error);
  }
}

// Call the async function
getEmojis();
```

**Comment by milesj** [comment]
@shinokada What's the http status being returned?

**Comment by shinokada** [comment]
![image](https://github.com/milesj/emojibase/assets/147320/99f60ce1-7ee0-473b-8d10-77a9787b49b1)

https://stackblitz.com/edit/js-t7pcbe?file=index.js

**Comment by milesj** [comment]
@shinokada 2.1.3 is extremely old, is there a reason you are using that? Try 15.3.0.
