### ISSUE TITLE
Minify published data

### ISSUE THREAD

**Issue by seangenabe** [milesj/emojibase#17]
Published JSON data should be minified to further reduce the overall file size.

**Comment by milesj** [comment]
I don't minify as I need to audit the git diff's when data changes. I have yet to figure out a good solution to this.

**Comment by seangenabe** [comment]
Can't you just audit the non-minified file? I guess then there'll be a minified and non-minified version of each file.

**Comment by milesj** [comment]
@seangenabe That's what I'm trying to avoid. It makes the diffs/commits/PRs far too large. I have an idea I need to try so I'll report back.

**Comment by milesj** [comment]
Found a way to solve this. Try out 3.1.0 and let me know how it works.
