### ISSUE TITLE
Exclude "repeated" emojis

### ISSUE THREAD

**Issue by raulriera** [milesj/emojibase#18]
Hi,

I was trying to find a common pattern to exclude the first version of an emoji that got extended in feature ones. For example, the police officer has the version where its only "officer" and then the next two which are "office male" and "officer female".

Without doing it manually, have you seen anything in the emoji data to filter the old versions?

Thanks

**Comment by milesj** [comment]
There's nothing in the data explicitly that I can recall, at most you'd have to check for the male/female codepoint at the end of the emoji hexcode.

**Comment by raulriera** [comment]
Thank you
