### ISSUE TITLE
Vietnamese language not published in v16.0.0

### ISSUE THREAD

**Issue by nolanlawson** [milesj/emojibase#183]
Hi, first off: thank you for continuing to maintain `emojibase`! It is a critical part of my [`emoji-picker-element`](https://github.com/nolanlawson/emoji-picker-element/) project. :grin: 

I noticed that, in [v16.0.0](https://github.com/milesj/emojibase/releases/tag/emojibase-data%4016.0.0), Vietnamese language support was added: https://github.com/milesj/emojibase/pull/179

However, there is no `vi` directory in [the published v16.0.0 files on npm](https://unpkg.com/browse/emojibase-data@16.0.0/).

It looks like it's possibly just a matter of running `yarn generate`. I tried this locally, and the correct `vi/` files were created.

Thank you again!

**Comment by milesj** [comment]
Hrmm the files definitely exist: https://github.com/milesj/emojibase/pull/179

I did switch to changesets for publishing, I wonder if it didn't publish correctly.

**Comment by milesj** [comment]
Actually looks like all files are missing. Releasing from CI doesn't have the non-raw files like my local does.

**Comment by milesj** [comment]
Ok got this all working now.
