### ISSUE TITLE
Emoji v12

### ISSUE THREAD

**Issue by milesj** [milesj/emojibase#20]
http://blog.unicode.org/2019/02/unicode-emoji-12-final-for-2019.html

**Comment by b-g** [comment]
+1! Please :)

**Comment by milesj** [comment]
Some of the v12 data files don't exist yet, so sadly can't work on this until they are added. Hopefully soon.

**Comment by b-g** [comment]
@milesj Ok + looking forward to! 

Probably not the right "issue" here ... but I really would like to thank you for all your efforts around emojibase! 🙏! Super mega helpful for our OpenMoji project! 🎩

**Comment by b-g** [comment]
Hi @milesj, This is a gentle ping for news :) Any news on v12? Would be super mega helpful to have the update. Sorry to bother you + Many thanks!

**Comment by milesj** [comment]
I believe I was blocked on this file: https://unicode.org/Public/12.0.0/ucd/UnicodeData.txt But it looks good to go now. I'll give the build another shot.

**Comment by b-g** [comment]
Yay! 👍🙏

**Comment by b-g** [comment]
Hi @milesj, A gentle ping for news :) Any news on v12? Would be super great to have this ready for out of the box use! Sorry to bother you!

**Comment by milesj** [comment]
A lot of new stuff was added in the v12 spec, so it isn't an easy upgrade. Will take me quite a bit to get it ready.

**Comment by milesj** [comment]
You can view it here: https://github.com/milesj/emojibase/pull/21

**Comment by raulriera** [comment]
Hi,

I have generated a script that takes the emojis from http://www.unicode.org/Public/emoji/12.0/ and dumps a JSON with all the content, but I am unable to find the datasource were you get the `keywords` from? Would you be willing to share that resource?

My script is

```ruby
require 'json'

current_category = ""
category_regex = /# group: ([\w &]+)/
emoji_regex = /([\w ]+) +;+ fully-qualified + #(...*?)([\w :,]+)/
all_emojis = []

File.readlines('emoji-test.txt').each do |line|
  if line.include? "# group: "
    current_category = category_regex.match(line).captures.first
  end

  if !line.start_with?("#") && line.include?("fully-qualified")
    begin
      utf, emoji, name = emoji_regex.match(line).captures

      all_emojis << { 
        :category => current_category,
        :name => name.strip!,
        :emoji => emoji.strip!,
        :hexcode => utf.strip!
      }

    rescue => error
      puts "REGEX ERROR: #{line}"
    end 
  end
end

File.open('emojis-generated.json', 'w') { |file| file.write(JSON.generate(all_emojis)) }
```

**Comment by milesj** [comment]
@raulriera It's a very involved process. All the locale aware data is in CLDR. http://cldr.unicode.org/

**Comment by b-g** [comment]
Hi @milesj, checked out your branch v12 to facilitate the data structure of our upcoming OpenMoji 2.0 release (1. week of May) ... it works + Yay! Quick question: is it safe to use [packages/data/en](https://github.com/milesj/emojibase/tree/v12/packages/data/en), or will there be more changes?

**Comment by milesj** [comment]
@b-g The structure shouldn't change, just the values of the fields. So it should be safe to use for prototyping at the moment.

**Comment by milesj** [comment]
@b-g The structure shouldn't change, just the values of the fields. So it should be safe to use for prototyping at the moment.

**Comment by b-g** [comment]
Hi @milesj! Sorry to bother you once more! Currently preparing our upcoming OpenMoji 2.0 release for next week ... while doing so, I've spotted that a lot of the `group` and `subgroups` values have changed. Now I'm wondering whether [packages/data/en/raw.json](https://github.com/milesj/emojibase/tree/v12/packages/data/en) of branch v12 is final and safe to use? I don't want to refactor all of OpenMoji and release a 2.0 with Emoji 12 data which is subject to change. Could you advice? Many thanks 🙏

<img width="235" alt="Screen Shot 2019-04-30 at 16 51 03" src="https://user-images.githubusercontent.com/480224/56970943-84c84900-6b68-11e9-9cbc-d92bc52f1a13.png">

**Comment by milesj** [comment]
@b-g Those are official. Direct from the data files: https://unicode.org/Public/emoji/12.0/emoji-test.txt

I'm also curious why you're trying to launch with v12 so soon, when iOS/Android/Windows do not support it yet (that I'm aware), and the CLDR data files are still in alpha. Seems a bit premature.

**Comment by milesj** [comment]
Only have a handful of errors to fix and this should be ready. Not sure why these are happening though.

```
[error]  ✖ No parent emoji found for skin tone: 1F468-1F3FC-200D-1F91D-200D-1F468-1F3FB (1)
[error]  ✖ No parent emoji found for skin tone: 1F468-1F3FD-200D-1F91D-200D-1F468-1F3FB (1)
[error]  ✖ No parent emoji found for skin tone: 1F468-1F3FD-200D-1F91D-200D-1F468-1F3FC (2)
[error]  ✖ No parent emoji found for skin tone: 1F468-1F3FE-200D-1F91D-200D-1F468-1F3FB (1)
[error]  ✖ No parent emoji found for skin tone: 1F468-1F3FE-200D-1F91D-200D-1F468-1F3FC (2)
[error]  ✖ No parent emoji found for skin tone: 1F468-1F3FE-200D-1F91D-200D-1F468-1F3FD (3)
[error]  ✖ No parent emoji found for skin tone: 1F468-1F3FF-200D-1F91D-200D-1F468-1F3FB (1)
[error]  ✖ No parent emoji found for skin tone: 1F468-1F3FF-200D-1F91D-200D-1F468-1F3FC (2)
[error]  ✖ No parent emoji found for skin tone: 1F468-1F3FF-200D-1F91D-200D-1F468-1F3FD (3)
[error]  ✖ No parent emoji found for skin tone: 1F468-1F3FF-200D-1F91D-200D-1F468-1F3FE (4)
[error]  ✖ No parent emoji found for skin tone: 1F469-1F3FB-200D-1F91D-200D-1F468-1F3FC (2)
[error]  ✖ No parent emoji found for skin tone: 1F469-1F3FB-200D-1F91D-200D-1F468-1F3FD (3)
[error]  ✖ No parent emoji found for skin tone: 1F469-1F3FB-200D-1F91D-200D-1F468-1F3FE (4)
[error]  ✖ No parent emoji found for skin tone: 1F469-1F3FB-200D-1F91D-200D-1F468-1F3FF (5)
[error]  ✖ No parent emoji found for skin tone: 1F469-1F3FC-200D-1F91D-200D-1F468-1F3FB (1)
[error]  ✖ No parent emoji found for skin tone: 1F469-1F3FC-200D-1F91D-200D-1F468-1F3FD (3)
[error]  ✖ No parent emoji found for skin tone: 1F469-1F3FC-200D-1F91D-200D-1F468-1F3FE (4)
[error]  ✖ No parent emoji found for skin tone: 1F469-1F3FC-200D-1F91D-200D-1F468-1F3FF (5)
[error]  ✖ No parent emoji found for skin tone: 1F469-1F3FC-200D-1F91D-200D-1F469-1F3FB (1)
[error]  ✖ No parent emoji found for skin tone: 1F469-1F3FD-200D-1F91D-200D-1F468-1F3FB (1)
[error]  ✖ No parent emoji found for skin tone: 1F469-1F3FD-200D-1F91D-200D-1F468-1F3FC (2)
[error]  ✖ No parent emoji found for skin tone: 1F469-1F3FD-200D-1F91D-200D-1F468-1F3FE (4)
[error]  ✖ No parent emoji found for skin tone: 1F469-1F3FD-200D-1F91D-200D-1F468-1F3FF (5)
[error]  ✖ No parent emoji found for skin tone: 1F469-1F3FD-200D-1F91D-200D-1F469-1F3FB (1)
[error]  ✖ No parent emoji found for skin tone: 1F469-1F3FD-200D-1F91D-200D-1F469-1F3FC (2)
[error]  ✖ No parent emoji found for skin tone: 1F469-1F3FE-200D-1F91D-200D-1F468-1F3FB (1)
[error]  ✖ No parent emoji found for skin tone: 1F469-1F3FE-200D-1F91D-200D-1F468-1F3FC (2)
[error]  ✖ No parent emoji found for skin tone: 1F469-1F3FE-200D-1F91D-200D-1F468-1F3FD (3)
[error]  ✖ No parent emoji found for skin tone: 1F469-1F3FE-200D-1F91D-200D-1F468-1F3FF (5)
[error]  ✖ No parent emoji found for skin tone: 1F469-1F3FE-200D-1F91D-200D-1F469-1F3FB (1)
[error]  ✖ No parent emoji found for skin tone: 1F469-1F3FE-200D-1F91D-200D-1F469-1F3FC (2)
[error]  ✖ No parent emoji found for skin tone: 1F469-1F3FE-200D-1F91D-200D-1F469-1F3FD (3)
[error]  ✖ No parent emoji found for skin tone: 1F469-1F3FF-200D-1F91D-200D-1F468-1F3FB (1)
[error]  ✖ No parent emoji found for skin tone: 1F469-1F3FF-200D-1F91D-200D-1F468-1F3FC (2)
[error]  ✖ No parent emoji found for skin tone: 1F469-1F3FF-200D-1F91D-200D-1F468-1F3FD (3)
[error]  ✖ No parent emoji found for skin tone: 1F469-1F3FF-200D-1F91D-200D-1F468-1F3FE (4)
[error]  ✖ No parent emoji found for skin tone: 1F469-1F3FF-200D-1F91D-200D-1F469-1F3FB (1)
[error]  ✖ No parent emoji found for skin tone: 1F469-1F3FF-200D-1F91D-200D-1F469-1F3FC (2)
[error]  ✖ No parent emoji found for skin tone: 1F469-1F3FF-200D-1F91D-200D-1F469-1F3FD (3)
[error]  ✖ No parent emoji found for skin tone: 1F469-1F3FF-200D-1F91D-200D-1F469-1F3FE (4)
[cache]  ✔ Using 12.0/emoji-source-list.json cached data
[validate] ✖ Error(s) detected for PERSON WITH BLOND HAIR (1F471):
 Invalid field subgroup. Found 8, require 22
[validate] ✖ Error(s) detected for BEARDED PERSON (1F9D4):
 Invalid field subgroup. Found 8, require 22
[validate] ✖ Error(s) detected for PERSON WITH BLOND HAIR, MALE SIGN (1F471-200D-2642-FE0F):
 Invalid field subgroup. Found 8, require 22
[validate] ✖ Error(s) detected for PERSON WITH BLOND HAIR, FEMALE SIGN (1F471-200D-2640-FE0F):
 Invalid field subgroup. Found 8, require 22
```

**Comment by b-g** [comment]
@milesj Many thanks for the clarification! We will go then with those. (Or when are you planning to fix the open issues above?)

OpenMoji is a non commercial project of the HfG Schwäbisch Gmünd (Design University South Germany), hence we are dependent on the "rhythm" of the semester. In addition we have been working on the project for 2 years and are very keen to have a real production ready set out there (feature complete with a recent Emoji/Unicode version). We had a lot of good feedback ... but people were not using the set in the projects/products as OpenMoji v1 is a bit all over the place in terms of Emoji Versions :)

**Comment by milesj** [comment]
Figured it out. It's all the new multi-group skin tone stuff: http://www.unicode.org/reports/tr51/#multiperson_skintones

**Comment by milesj** [comment]
Just a bit of polish left and I'll tag an alpha release.

**Comment by b-g** [comment]
Yay! Super. Looking forward to the new release! Thanks!

**Comment by b-g** [comment]
Hi @milesj, quick feedback: 
1. Could already make use the new files. Very helpful! 🙏
2. The new data contains quite a few of `"single hexcode"-FE0F`emojis. Is this on purpose? This is create a lot of "redundant" data ... do you know the intention of these additions?

<img width="534" alt="Screen Shot 2019-05-03 at 17 46 21" src="https://user-images.githubusercontent.com/480224/57149157-657d2600-6dcb-11e9-9aec-7df0b7b7136c.png">

[list.csv.zip](https://github.com/milesj/emojibase/files/3142615/list.csv.zip)

**Comment by milesj** [comment]
Yeah, I don't know what the best course of action for those are yet. v12 added "emoji only" variants, while the variants without `-FE0F` are the pre-emoji text variant. I'm leaning towards merging them and relying on the v12 variant.

**Comment by milesj** [comment]
This is "ready". Going to merge the PR and tag an alpha release. Let me know if there are any issues, and if not, I'll tag an official release soon.

**Comment by b-g** [comment]
@milesj Yay! In terms of feedback just 👍 and 🙏 from my end! 👀 forward to the alpha release!

> I'm leaning towards merging them and relying on the v12 variant.
+1 makes sense ... just document the decision in the docs

**Comment by milesj** [comment]
Ended up doing the reverse: https://milesj.gitbook.io/emojibase/spec#merged-variation-selectors

Anyways, alpha releases available! I'll leave this issue open for feedback.

**Comment by KwanEsq** [comment]
Tested with twemoji-colr updated to twemoji 12.0.1, seems good so far.  Thanks for including the skin tones, means I can remove manually adding them.

**Comment by b-g** [comment]
Works for me too! Seems to be a good solution!

I think I would add these two comments to make the code example https://milesj.gitbook.io/emojibase/spec#merged-variation-selectors more verbose:

```js
{
  "annotation": "copyright",
  "name": "COPYRIGHT SIGN",
  "hexcode": "00A9",
  "emoji": "©️", // 00A9-FE0F
  "text": "©︎", // 00A9-FE0E
  // ...
}
```

**Comment by milesj** [comment]
Good idea! Thanks for the feedback, much appreciated.

**Comment by milesj** [comment]
Tagged officials, enjoy!

**Comment by b-g** [comment]
Yay! ❤️ ✅
