### ISSUE TITLE
emojis in wrong catecory

### ISSUE THREAD

**Issue by supertiger1234** [milesj/emojibase#22]
Looking at telegram, discord and also https://emojipedia.org/nature/ , it lookes like some emojis are not in the right category. for example, the fire emoji should be in animals-nature, but in emoji-base, its in nature.

**Comment by milesj** [comment]
@supertiger1234 The categories in emojibase are based on the official unicode data files: https://www.unicode.org/Public/emoji/12.0/emoji-test.txt

**Comment by supertiger1234** [comment]
Hmm :thinking: is there anyway I could make my own categories?

**Comment by milesj** [comment]
@supertiger1234 Youd have to map over the data and change all the groups/subgroups manually. Going to close this for now.

**Comment by supertiger1234** [comment]
I just copied the compact.json file to my source folder and modified some stuff, worked out well :D
