### ISSUE TITLE
Regex: Matching of unqualified bytes (©®™)

### ISSUE THREAD

**Issue by dbrgn** [milesj/emojibase#37]
It seems that the the default regex (`import EMOJI_REGEX from 'emojibase-regex'`), the emoji regex (`import EMOJI_REGEX from 'emojibase-regex/emoji'`) and also the text regex (`import EMOJI_REGEX from 'emojibase-regex/text'`) all match non-qualified characters like the copyright sign.

As far as I know, the copyright sign is text-default (https://emojipedia.org/emoji/%C2%A9/), so there should be a "non-greedy" regex that does not match the copyright sign without an emoji variant selector, right? Is there such a regex in this project?

Other text-default emoji include the [warning sign](https://emojipedia.org/emoji/%E2%9A%A0/) or the [biohazard sign](https://emojipedia.org/emoji/%E2%98%A3/). See also: http://xahlee.info/comp/text_vs_emoji.html

Have I imported the wrong regex?

**Comment by dbrgn** [comment]
I noticed that in the raw data (https://github.com/milesj/emojibase/blob/master/packages/data/en/raw.json) the copyright and trademark signs are marked as "emoji-default" (type=1). Isn't that wrong?

**Comment by milesj** [comment]
@dbrgn Here's the data file that contains those characters: https://unicode.org/Public/emoji/12.0/emoji-data.txt. Unless I'm reading this incorrectly, they are marked as emoji based on the `Emoji` property.

Side note, looks like there's new data files I'll have to parse: https://unicode.org/Public/emoji/12.1/

**Comment by milesj** [comment]
Tracking updates here: https://github.com/milesj/emojibase/pull/38

Will look into spec issues as well.

**Comment by dbrgn** [comment]
@milesj thanks!
