### ISSUE TITLE
Wrestlers (People, Men, Women) should have skintones?

### ISSUE THREAD

**Issue by b-g** [milesj/emojibase#40]
Hi @milesj! 

I think the Wrestlers (People, Men, Women) should have skintones as of Unicode 3.0/4.0 (at least Emojipedia says that). The `raw.json`(https://github.com/milesj/emojibase/tree/master/packages/data/en) doesn't have them. Is this a mistake or is Emojipedia wrong?

https://emojipedia.org/men-wrestling/
https://emojipedia.org/women-wrestling/
https://emojipedia.org/wrestlers/

PS. Many thanks for the 12.1 update! Keep up the good work! 🙏 Really great to have the emojibase project!

**Comment by milesj** [comment]
@b-g Nice catch, I wonder why 🤔 

Have you noticed this on any others?

**Comment by milesj** [comment]
It looks like the skin tones are missing from the ZWJ source files: 

- http://unicode.org/Public/emoji/12.1/emoji-zwj-sequences.txt
- https://www.unicode.org/Public/emoji/12.1/emoji-test.txt

I'm not entirely sure where emojipedia is getting their data from.

**Comment by b-g** [comment]
@milesj 
Many thanks for looking into it! 

I became aware of this potential bug as our OpenMoji Project got a request to "[Support all ZWJ sequences](https://github.com/hfg-gmuend/openmoji/issues/96)" ... as far as I understand it only Microsoft is supporting the mentioned ones (I think OpenMoji should just support the really official ones). But still I quickly double checked all of them at Emojipedia. The Wrestlers emojis were the only ones which are "official" according to Emojipedia. So:

> Have you noticed this on any others?

No, just the Wrestlers ... but if they are missing form the unicode ZWJ source files ... maybe the bug is on Emojipedia side? Or any aware of other way to validate the skintones of the Wrestlers?

**Comment by milesj** [comment]
They're not listed here either: https://unicode.org/emoji/charts-12.1/full-emoji-modifiers.html

I'm leaning towards emojipedia logging additional data besides the official spec.

**Comment by b-g** [comment]
Should we simply leave with that (and ignore Emojipedia) or ping Jeremy Burge from Emojipedia asking him what is going on? I have his contact and are in touch with him infrequently ... happy to loop you in if interested. Either way is fine for me.

**Comment by milesj** [comment]
Yeah, some confirmation from emojipedia would be fantastic.

**Comment by b-g** [comment]
@milesj Email to emojipedia is out ... will keep you posted if there is a response.

**Comment by b-g** [comment]
@milesj Feedback from Emojipedia ... the skintones of the wrestlers are not official unicode ... but were briefly in the past. 

> these are one of the few RGI emoji sequences removed after implemented. They were recommended, briefly, but now they are not.
> For compliance with Emoji 12.1, you wouldn’t need to include them. So technically not a bug, it was a deliberate choice to revoke the sequences.

Will close the issue. Thanks!

cc @carlinmack

**Comment by milesj** [comment]
Awesome, thanks for clarifying!
