### ISSUE TITLE
Emoji v13

### ISSUE THREAD

**Issue by b-g** [milesj/emojibase#45]
Hi @milesj! It seems Unicode has finalized the list https://unicode.org/emoji/charts-13.0/emoji-released.html ... wink wink :)

**Comment by milesj** [comment]
Looks like they moved the source files around, https://unicode.org/Public/emoji/13.0/, and also:

```
- The emoji specification (UTS #51) will have additional guidelines on gender and skin tone, and other clarifications. The definitions in UTS #51 and data files have been enhanced to be more consistent and useful. The final text will be available on March 10.
- The CLDR names and search keywords for the new emoji in over 80 languages, and the sort order for emoji, will be finalized by mid-April with the release of CLDR v37.
```

So this will take some custom work and probably won't land until late February.

**Comment by b-g** [comment]
Many thanks for the investigation! We didn't look that close :) Fingers crossed that it lands soon! Cheers!

**Comment by milesj** [comment]
Starting here: https://github.com/milesj/emojibase/pull/46

**Comment by b-g** [comment]
Hi @milesj! Ping :) Any info on the very rough timeline? 

It would be extremely handy for us to have emojibase emoji v13 as all our workflows rely on it. We already have 20% of the new emoji v13 ... and are keen to add the remaining ones. Sorry to bother! This just our enthusiasm for all the new emojis. 

Many thanks!

**Comment by milesj** [comment]
@b-g I looked into it last week and the source data files weren't in a usable state yet. I'll look again soon.

**Comment by carlinmack** [comment]
https://www.unicode.org/versions/Unicode13.0.0/ it's official :D

**Comment by milesj** [comment]
I think it's ready 🤔

**Comment by b-g** [comment]
Yay!

**Comment by milesj** [comment]
Enjoy!

**Comment by b-g** [comment]
Mega! Just upgraded OpenMoji to the latest! Many thanks!!
