### ISSUE TITLE
Support multiple shortcode presets

### ISSUE THREAD

**Issue by milesj** [milesj/emojibase#49]
There is no standard for shortcodes (`:smile:`), so every website/platform (Slack, GitHub, etc) have different implementations. Furthermore, emojibase implements its own version (since there is no standard to reference from), which results in common emojis having different shortcodes (people don't like this).

Ideally I would like to support shortcode presets from multiple sources, but I'm not entire sure where I could get this information. In an ideal world, it would look like the following:

- Remove `shortcodes` from all `emojibase-data`.
- Add new `emojibase-data/shortcodes/*.json` datasets that map hexcodes to an array of custom shortcodes for each emoji.
- Have the consumer load and stitch them together.

**Comment by gavinr** [comment]
Follow-up or example for this:

The popular https://github.com/iamcal/js-emoji library uses https://github.com/iamcal/emoji-data. Their shortcodes can be seen [here](https://unicodey.com/emoji-data/table.htm) and the source is [here](https://github.com/iamcal/emoji-data/blob/master/emoji.json) (see `short_name` property). Note that these are slightly different than the shortcodes in this repository.

I'm not saying which is right or wrong, but I'll echo that as a user it's annoying and would be great if places could start to standardize. Thanks for the hard work!

**Comment by milesj** [comment]
Supported in the next major.
