### ISSUE TITLE
No skintones for 🤝 Handshake?

### ISSUE THREAD

**Issue by b-g** [milesj/emojibase#50]
If I'm not mistaken then there are no skintones for  🤝 "Handshake" 1F91D in emojibase-data, or? But https://emojipedia.org/search/?q=handshake and other vendors are having them ... is this again a non-official Unicode thing like #40?

**Comment by milesj** [comment]
They're official but does look like they're missing. Odd 🤔

**Comment by b-g** [comment]
👍 + Thanks!

**Comment by milesj** [comment]
@b-g So this is weird, I really don't know the answer. 

Supposedly these skin tones were added in v3, which you can see here: https://unicode.org/Public/emoji/3.0/emoji-sequences.txt

But in the latest versions (v12, v12.1, v13), those handshake entries no longer exist: https://unicode.org/Public/emoji/12.0/emoji-sequences.txt

They seemed to have disappeared in v4. https://unicode.org/Public/emoji/5.0/emoji-sequences.txt

And according to this thread, they were never official. https://github.com/twitter/twemoji/issues/192

**Comment by milesj** [comment]
After a bit more digging, ti seems this is also true for apple devices, there are no skin tones. The reasoning is because there are 2 hands in the emoji, so which skin tone would apply to which?

**Comment by b-g** [comment]
Many thanks for looking into this mystery! :)

As multi-skintones exist e.g. https://openmoji.org/library/#emoji=1F9D1-1F3FB-200D-1F91D-200D-1F9D1-1F3FF I don't get why Handshake is treated differently by Unicode. Anyways great that you've investigated. 

Should we leave it open or close it? 

I guess we could also file an issue at Unicode? cc @carlinmack

**Comment by milesj** [comment]
@b-g Yes multi-skin tones exist, but it depends on the spec implementing them. There's a handful of emoji that could use skin tones/modifiers, but do not, so it's probably just a time constraint.

**Comment by milesj** [comment]
This is most likely landing in v14 https://github.com/milesj/emojibase/pull/129
