### ISSUE TITLE
Alias "tada" to "hooray"

### ISSUE THREAD

**Issue by tredondo** [milesj/emojibase#52]
(and maybe "confetti" as well?)

![image](https://user-images.githubusercontent.com/10043369/80038670-3dda1d00-854a-11ea-8160-d1ef243bab99.png)

**Comment by nolanlawson** [comment]
Looks like both `:tada:` and `:hooray:` are supported now in v6 depending on the shortcodes source (GitHub versus Emojibase):

https://github.com/milesj/emojibase/blob/5bb6aae3d5f2d3e7c9232b7fdd691baa212f2ff8/packages/data/en/shortcodes/github.raw.json#L1637

https://github.com/milesj/emojibase/blob/6e2faba180d2299c52762c11693f1a2414681a43/packages/data/en/shortcodes/emojibase.raw.json#L3222

Seems this issue can be closed?

**Comment by milesj** [comment]
It can! Thanks.
