### ISSUE TITLE
Regex fails to match many emoji symbols

### ISSUE THREAD

**Issue by rgrove** [milesj/emojibase#6]
The emojibase regex fails to match quite a few symbols. Here's a quick example showing all the unmatched symbols I've been able to find:

```js
const emojibaseRegex = require('emojibase-regex');
const emojis = '😐👽👍👎👈👉👆👇🖐👂👁🗣🕴👪🎓⛑👓🕶🐦🕷🕸🐟🐕🐈🕊🐿🌎🌍🌏🌕🌜🌤🌥🌦🌧⛈🌩🌨🌬🌪🌫🌶🍸🍽⛸⛷🏂🏄🏊🎖🏆🏵🎗🎟🎭🎬🎧🎮🏎🚑🚲🏍🚔🚍🚘🚇🛩🛰🛥🛳⛴🗺🏟⛱🏖🏝⛰🏔🏜🏕🛤🛣🏗🏭🏠🏘🏚🏛⛩🏞🏙💻🖥🖨🖱🖲🕹🗜💿📷📹📽🎞📟📺📻🎙🎚🎛⏱⏲🕰⏳🕯🗑🛢💰💳⚒🛠⛏⛓💣🗡🛡🕳🌡🛎🗝🛋🛏🖼🛍📥📤📦🏷📪📫📬📭🗒🗓🗃🗳🗄📋🗂🗞📚🖇🖊🖋🖌🖍🔍🔒🔓🕉🚭❓🚹🚺🚼⏸⏯⏹⏺⏭⏮⏩⏪🔈👁‍🗨🗯🕐🕑🕒🕓🕔🕕🕖🕗🕘🕙🕚🕛🕜🕝🕞🕟🕠🕡🕢🕣🕤🕥🕦🕧';

emojis.match(emojibaseRegex);
// => null
```

I spent some time poking around to see if I could find the root cause and open a PR, but ran out of time to work on this today so I figured I'd at least report it.

**Comment by milesj** [comment]
That's a bid odd since I loop over every emoji character and test it: https://github.com/milesj/emojibase/blob/master/packages/emojibase-regex/tests/regex.test.js#L17

I wonder where the issue is. Maybe it's a text vs emoji variation selector.

**Comment by milesj** [comment]
Ok, I think I know the problem. All of these look like variation selectors: http://unicode.org/Public/emoji/5.0/emoji-variation-sequences.txt

Technically there are 3 variations, unicode character, unicode character + emoji presentation, unicode character + text presentation. One of them might be missing, digging further.

**Comment by milesj** [comment]
Just tagged a new version. Let me know if that resolves it.

**Comment by rgrove** [comment]
Looks like that solved the problem. Thanks! 🍻

**Comment by milesj** [comment]
@rgrove Awesome, thanks for reporting the issue!
