### ISSUE TITLE
Add more locales

### ISSUE THREAD

**Issue by strixaluco** [milesj/emojibase#62]
May I ask to add support for Ukrainian language? 
Also, based on [translation status](https://translate.riot.im/projects/element-web/#languages) of Element Web and according to occurrence of particular language speakers in [Element translation room](https://matrix.to/#/!yvhoprZiKmhjxKfNHa:matrix.org?via=matrix.eclabs.de&via=matrix.org&via=tchncs.de), I would suggest adding Estonian, Finnish, Hungarian, Lithuanian and Norwegian languages as well if that's possible.
Thanks.

**Comment by milesj** [comment]
@strixaluco Sure! Progress here https://github.com/milesj/emojibase/pull/63

**Comment by strixaluco** [comment]
Thank you again!

**Comment by milesj** [comment]
@strixaluco Done, pretty easy. I'll release these alongside the shortcode changes.

Only thing to note about these locales is that Norwegian is only `nb` and doesn't support `nb_NO`, `no`, or `no_NO`.

**Comment by strixaluco** [comment]
Truly appreciate it.
Sure, let's hope `nb` will serve Norwegian users well. Cheers.
