### ISSUE TITLE
Group and subgroup seem to have the same value

### ISSUE THREAD

**Issue by kaiphi** [milesj/emojibase#8]
Hey there,
I just stumbled upon your emojibase lists some days ago – such a nicely ordered and useful list of all the emojis – great work!
However we realized that the numbers of the group and subgroup are equal to eachother. The group numbers seem to be perfectly fine but the subgroups turn out to be faulty.
It would be really great if that issue could be fixed! We're so glad to have found your database and it would make us even happier if we were able to make use of the subgroups in near future, too!

Best regards,
Kai

**Comment by milesj** [comment]
Hey @kaiphi,

Can you explain in what ways the subgroups are wrong? After looking at the parser and current dataset, it seems correct.

The numbers shouldn't really be relied upon, they aren't deterministic and can change between emoji releases. Both groups and subgroups are 0-index based with their own counters.

**Comment by kaiphi** [comment]
Hey @milesj,
thanks for your fast reply! We found this issue within the .json data files (https://github.com/milesj/emojibase/blob/master/packages/emojibase-data/en/data.json).
In the json file, the highest value for subgroups is 7 – although there should be more subgroups than that I guess (there are more subgroups in the emoji-test.txt, too). Thanks for further help!

**Comment by milesj** [comment]
@kaiphi Ah I see, I was looking in the "meta/groups.json" file.

This should now be fixed though, thanks!
