### ISSUE TITLE
Supporting Unicode Emoji 13.1 ?

### ISSUE THREAD

**Issue by b-g** [milesj/emojibase#81]
Hi @milesj, 

Hope you've had a nice start into 2021 despite the depressing times!

As usual ... any timeline on supporting Unicode Emoji 13.1? :)

**Comment by milesj** [comment]
Thanks for reminding me. Will probably get around to it sometime this week or the next.

**Comment by milesj** [comment]
This has landed https://github.com/milesj/emojibase/blob/master/packages/data/CHANGELOG.md

👍

**Comment by b-g** [comment]
Mega! Many thanks!!
