### ISSUE TITLE
New groups?

### ISSUE THREAD

**Issue by fhnsjw** [milesj/emojibase#88]
The website says for the Data Structure of the dataset:

```
group (number) - The categorical group the emoji belongs to, ranging from 0 (smileys) to 7 (flags). Undefined for uncategorized emojis.
```

but it seems that the groups range from 0 to 9. One of these groups seems to have only about 10 emojis? Is that part of the website outdated, or am I doing something wrong?

**Comment by milesj** [comment]
@fhnsjw The docs are outdated, all the groups can be seen here: https://github.com/milesj/emojibase/blob/master/packages/data/meta/groups.json

I'll update the docs, thanks.
