### ISSUE TITLE
Add emoji reference to meta files

### ISSUE THREAD

**Issue by ialokim** [milesj/emojibase#9]
First thanks a lot for your great library!

While working with its meta json files, I've noticed I would find it very useful to have objects instead of arrays for `shortcodes.json`. The keys would be the actual shortcode and as a value I would expect a reference to the actual emoji information. I've thought about a simple integer with the emoji's `order` property, so that you can get the emoji from your (already ordered) `data.json` simply using the index.

I think this could also be useful for the `hexcodes.json` and `unicode.json` files. If you agree, I would be happy to make a PR with the necessary changes, but I wanted to discuss it here first.

**Comment by milesj** [comment]
So what you're looking for is a map with the key being the shortcode and the value being the full emoji object? If so, I've been steering away from that as the filesize would be quite large.

To get around this however, I've been generate custom datasets from the emoji dataset, like so: https://github.com/milesj/interweave/blob/master/packages/interweave-emoji/src/EmojiData.js#L112

**Comment by ialokim** [comment]
> So what you're looking for is a map with the key being the shortcode and the value being the full emoji object? If so, I've been steering away from that as the filesize would be quite large.

Not exactly, I wanted a map with the key being the shortcode and the value being the `emoji_order` as in the `data.json`. See this little example:
```json
{
  "interrobang": 12,
  "exclamation_question": 44,
  "tm": 345,
  "info": 344,
  "arrow_left_right": 25
}
```

With the help of these indexes, we could retrieve the actual emoji data from `data.json`.

**Comment by milesj** [comment]
This is doable but do note that his approach would not work with skin tone modifiers.

**Comment by ialokim** [comment]
> This is doable but do note that his approach would not work with skin tone modifiers.

Oops that's weird, so we couldn't use these indexes directly on the data array in any case, because the skin modifiers have an `order` key too, right?

**Comment by milesj** [comment]
It's a bit tough. Skin tones are a nested array within their parent emoji: https://github.com/milesj/emojibase/blob/master/packages/emojibase-test-utils/test-data.json#L2309

They do have an `order`, but are not indexed as such, since it's not a flat array. So using order/index isn't entirely accurate.
