### ISSUE TITLE
Is it possible to add additional tags?

### ISSUE THREAD

**Issue by aoisensi** [milesj/emojibase#92]
Hello.
Can you add additional tags to `pleading_face` :pleading_face: `U+1F97A` in Japanese?
Most Japanese call the emoji `ぴえん` (PIEN).
This is a famous meme and is written about in [Wikipedia](https://ja.wikipedia.org/wiki/%E3%81%B4%E3%81%88%E3%82%93).
Thank you!

**Comment by milesj** [comment]
@aoisensi Shortcodes can be added here: https://github.com/milesj/emojibase/blob/master/po/ja/shortcodes.po#L8678 

But most of this file has not been translated yet.
